### ISSUE TITLE
Silicon Mac version sometime soon?

### ISSUE THREAD

**Issue by theEpicjosh** [RafPlayz69YT/FLPTrialStateModder#1]
Hello,

Just wanted to say, I love your FLP Trail State Modder. It helped me get back into FL Studio.
I was just wondering if there was a _Mac version_ (specifically Silicon) coming out in the near future.

In any case, thank you for this cool product!
- Josh

**Comment by raf13lol** [comment]
sorry, can't compile to mac unless on mac itself. i have heard about a program called wine which allows you to run .exes on mac and linux, not sure about any other details about it. maybe try find a tutorial online for .exe running on mac? i could try a vm but last time i tried, it didn't work.

**Comment by raf13lol** [comment]
quick note: trying again for the mac vm, ill let you know if it works

**Comment by raf13lol** [comment]
works, expect a mac version in the releases tab soon

**Comment by theEpicjosh** [comment]
Ah, cool! Thanks!

**Comment by raf13lol** [comment]
yea sorry but it wouldnt install, kept rebooting midway through, sorry about getting your hopes up tho, ill have a few more attempts and that'll be it

**Comment by theEpicjosh** [comment]
That's alright!
