### ISSUE TITLE
fl studio crashes 

### ISSUE THREAD

**Issue by yasientrabih27** [RafPlayz69YT/FLPTrialStateModder#6]
my fl studio crashes on windows 10 11 from your FLTrialStateModder could you fix this bug? will there be a mac version or linux 

very nice app

**Comment by yasientrabih27** [comment]
![Schermopname (1)](https://github.com/raf13lol/FLPTrialStateModder/assets/160323198/5587e82c-0ee3-4bb4-810e-726fb1835867)

**Comment by raf13lol** [comment]
fl studio 21 is not supported, and will not most likely be ever
